### ISSUE TITLE
GEM texture focusing, mismatch between number of vanadium banks and cropping values

### ISSUE THREAD

**Issue by josephframsay** [mantidproject/mantid#22710]
**Original reporter:** Winfried Kockelmann, ISIS (also worth speaking to Saurabh Kabra, as he wrote the original scripts)

**Note this is a high priority for ISIS Powder for 3.14**

The new texture capabilities in `isis_powder` for GEM, while seeming to run fine in testing, failed as soon as we tried to show them to GEM scientists. Specifically, when running `create_vanadium` we got the mismatch error from `common.crop_banks_using_crop_list`, as `isis_powder` provides 160 cropping values (in texture mode), but for some reason the vanadium was focused into 162.

Though Winfried sent me his cycle mapping file, I couldn't reproduce the error on my machine, and I suspect that the failed run wasn't using the right vanadium. We should take a cycle mapping file which we know to work with texture mode up there and see if that fails.
```
83881-84212:
  label: "cycle_17_3"
  offset_file_name: "offsets_2011_cycle111b.cal"
  Rietveld:
    vanadium_run_numbers: "83883" #VNb
    empty_run_numbers: "83884"
  PDF:    
    vanadium_run_numbers: "83883" #VNb
    empty_run_numbers: "83884"
```

A few ideas:
- I suspect the issue may be that something secret and evil in `DiffractionFocussing` is just discarding any banks that don't have data in, and the vanadium run we're using just happens to have the right number thrown out that we end up with 160. This is slightly complicated by the fact that I've tried it with lots of different vanadiums, and none of them gave this mismatch
- The grouping file contains 164 banks. This is weird, as the whole point is that we focus into 160, so try and investigate why this is (this will be hard, as it was made by a sandwich student in days of yore, and scientists don't seem to remember much about it). It's possible that we may need to create another grouping file which does this properly (I don't think it will come to this)
