### ISSUE TITLE
Migrate Linux PR check to a github action

### ISSUE THREAD

**Issue by thomashampson** [mantidproject/mantid#37628]
**Describe the outcome that is desired.**
Move the Linux build and {unit+system} test PR check to a GitHub action.

**Additional context**
Currently it runs on Jenkins, but we would like to move away from this.

**Comment by idigs** [comment]
@thomashampson's initial work on this:

https://github.com/thomashampson/mantid_github_actions_test/blob/testing-linux-pr-workflow-2/.github/workflows/linux_build_and_test.yml

```
name: Linux unit tests and system tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  linux-build-and-test:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
        with:
          # Needed to fetch tags for versioningit
          fetch-depth: "0"
      
      - name: Run unit tests and system tests on Linux
        run: ${GITHUB_WORKSPACE}/buildconfig/Jenkins/Conda/conda-buildscript ${GITHUB_WORKSPACE} linux-64-ci --enable-systemtests

      - name: Upload build and test log artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          path: ${{ github.workspace }}/build/test_logs/*.log

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: |
            ${{ github.workspace }}/build/test_logs/junit.xml
```
